---
baseURL: "https://aws-cloud-clubs.github.io/"
title: AWS Student Clubs
theme: papermod
buildFuture: true
paginate: 5

minify:
  disableXML: true

outputs:
  home:
    - HTML
    - JSON

taxonomies:
  category: categories
  series: series
  tag: tags

params:
  env: production
  description: AWS Student Clubs
  author: Subin Kim

  ShowShareButtons: false
  ShowReadingTime: false
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowToc: false

  homeInfoParams:
    Title: AWS Student Clubs
    Content: |
      â˜ï¸ AWS Student Clubì€ AWS ê¸°ìˆ ì— ê´€ì‹¬ìˆëŠ” ëŒ€í•™ìƒë“¤ì´ ëª¨ì—¬ í´ë¼ìš°ë“œ ê¸°ìˆ ì„ ê³µë¶€í•˜ê³  ì „íŒŒí•˜ëŠ” ëŒ€í•™ ë‹¨ìœ„ì˜ AWS ë™ì•„ë¦¬ì˜ˆìš”.

      ğŸ™‹ğŸ» 8ê°œì˜ ëŒ€í•™ê³¼ ê° í•™êµì—ì„œ ì„ ë°œëœ 10ëª…ì˜ ìº¡í‹´ì´ í•¨ê»˜í•˜ê³  ìˆìœ¼ë©°, ì´ 10ëª…ì˜ ìº¡í‹´ë“¤ì€ AWSKRUG University Student Group(AUSG)ì˜ í™œë™ ë©¤ë²„ë“¤ì´ì—ìš”.

  profileMode:
    enabled: true
    title: AWS Student Clubs
    imageUrl: "/images/logo.png"
    imageTitle: AWS Student Clubs Logo
    imageWidth: 200
    imageHeight: 200
    buttons:
      - name: Intro
        url: intro
      - name: Namseoul University
        url: series/namseoul-university
      - name: Kyung Hee University
        url: series/kyung-hee-university
      - name: SEOULTECH
        url: series/seoultech
      - name: Soongsil University
        url: series/soongsil-university

  socialIcons:
    - name: github
      url: "https://github.com/aws-cloud-clubs"
    - name: notion
      url: "https://ausg-7th.notion.site/2023-AWS-Student-Club-f943ac414afa45659f0440b03e0fb2af"

  editPost:
    URL: "https://github.com/aws-cloud-clubs/aws-cloud-clubs.github.io/tree/main/content"
    Text: "Edit"
    appendFilePath: true

  assets:
    disableHLJS: true
    favicon: "/images/favicon.ico"
    favicon16x16: "/images/favicon-16x16.png"
    favicon32x32: "/images/favicon-32x32.png"

  cover:
    hiddenInSingle: true
    responsiveImages: true

services:
  instagram:
    disableInlineCSS: true
  twitter:
    disableInlineCSS: true
